language: python

python:
  - "3.6"
  - "3.6-dev" # 3.6 development branch
  - "nightly" # currently points to 3.7-dev

os:
  - linux

matrix:
  allow_failures:
  - python: "3.6-dev"
  - python: "nightly"
  include:
    - python: 3.7
      dist: xenial

install:
  - pip install codecov
  - pip install coverage

script:
  - coverage run setup.py test

after_success:
  - coverage report
  - codecov